version: "2.0"

services:
  database:
    image: postgres:12
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kalaha
      SPRING_PROFILES_ACTIVE: compose
    ports:
      - 15432:5432
  kalaha:
    build: .
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 15432
      POSTGRES_DATABASE: kalaha
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: local
    ports:
      - 8080:8080
    depends_on:
      - database
